Importing the required libraries.

In [ ]:
import numpy as np
import pandas as pd

Load data

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Data before transformation.csv to Data before transformation.csv

In [ ]:
df = pd.read_csv('Data before transformation.csv')

In [ ]:
df

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,YQT77A2J44CPMV7H28J9V30ADR,8667639.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,"Furnished apartment for rent in Al Rehab, 250M",55000.0,...,False,NaN,4456.0,Escan Group,aahmdymagdy201070@gmail.com,2.011233e+11,2.011040e+11,2.022126e+10,atiasaad188@gmail.com,2026-03-05T00:43:04.172513
39709,8385GKAA00BXE8FYPWNQ29VF3M,8667632.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,45000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010947e+11,2.022126e+10,yuliya.hassan@remax.com.eg,2026-03-05T00:43:04.172513
39710,R9PTSC3V5RZ77ZT9X69TBE1PEC,8667625.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/town...,Townhouse,Residential for Rent,NaN,Furnished villa for rent in Town 5 rooms near New,120000.0,...,False,NaN,4679.0,Abrag 2,NaN,NaN,2.011146e+11,2.022126e+10,Mahmoudalabasy94@gmail.com,2026-03-05T00:43:04.172513
39711,9Q295E8B6ET3V30Z31925BR6ZG,8667615.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,For Rent – Premium 196m² Fully Finished Apartment,50000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010707e+11,2.022126e+10,yalashwat2000@gmail.com,2026-03-05T00:43:04.172513
39712,HYEPN5XPWQT7K05K4ST7EDWW5R,8667602.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,If you're looking hotel units contact us now,75000.0,...,False,English | Arabic,5307.0,Smart Home,ahmedbompo9@gmail.com,2.010120e+11,2.010408e+11,2.022126e+10,sh2927333@gmail.com,2026-03-05T00:43:04.172513

Important columns For this project

In [ ]:
selected_columns = [
    "category",
    "property_type",
    "price_egp",
    "area_value",
    "bedrooms",
    "bathrooms",
    "city",
    "town",
    "district",
    "completion_status",
    "listed_date",
    "furnished",
    "amenities",
    "payment_method"
]

In [ ]:
df = df[selected_columns]

# عرض النتيجة
print(df.head())

  category property_type   price_egp  area_value bedrooms bathrooms   city  \
0      buy        Duplex  24500000.0       445.0        3         6  Cairo
1      buy     Apartment   5145000.0       123.0        2         2   Giza
2      buy     Apartment  10800000.0       250.0        4         4  Cairo
3      buy     Apartment  10500000.0       136.0        2         2  Cairo
4      buy         Villa  19500000.0       255.0        4         4  Cairo

                town                district completion_status  \
0     New Cairo City      The 5th Settlement         completed
1  Sheikh Zayed City  Sheikh Zayed Compounds          off_plan
2     New Cairo City      The 5th Settlement         completed
3     New Cairo City      The 5th Settlement         completed
4     New Cairo City      The 5th Settlement         completed

            listed_date furnished  \
0  2026-03-03T19:15:06Z       NaN
1  2026-03-04T11:24:23Z    PARTLY
2  2026-03-04T14:03:51Z       NaN
3  2026-03-04T12:38:11Z       YES
4  2026-03-03T09:45:41Z       NaN

                                           amenities payment_method
0  Balcony | Built in Wardrobes | Covered Parking...           cash
1  Balcony | Built in Wardrobes | Central A/C | C...           cash
2  Balcony | Built in Wardrobes | Central A/C | C...           cash
3  Balcony | Built in Wardrobes | Central A/C | C...           cash
4  Balcony | Built in Wardrobes | Central A/C | C...           cash

Exploratory Data Analysis (EDA) — analyzing and understanding the dataset to discover patterns, relationships, and key insights.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39713 entries, 0 to 39712
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   category           39713 non-null  object
 1   property_type      39712 non-null  object
 2   price_egp          39712 non-null  float64
 3   area_value         39712 non-null  float64
 4   bedrooms           39678 non-null  object
 5   bathrooms          39683 non-null  object
 6   city               39712 non-null  object
 7   town               39712 non-null  object
 8   district           39366 non-null  object
 9   completion_status  19763 non-null  object
 10  listed_date        39712 non-null  object
 11  furnished          31328 non-null  object
 12  amenities          39680 non-null  object
 13  payment_method     19939 non-null  object
dtypes: float64(2), object(12)
memory usage: 4.2+ MB

In [ ]:
df.isnull().sum()

category                 0
property_type            1
price_egp                1
area_value               1
bedrooms                35
bathrooms               30
city                     1
town                     1
district               347
completion_status    19950
listed_date              1
furnished             8385
amenities               33
payment_method       19774
dtype: int64

In [ ]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique())
    print("-" * 50)

Column: category
['buy' 'rent']
--------------------------------------------------
Column: property_type
['Duplex' 'Apartment' 'Villa' nan 'Penthouse' 'Twin House' 'Townhouse'
 'Chalet' 'iVilla' 'Hotel Apartment' 'Whole Building' 'Half Floor' 'Land'
 'Bulk Sale Unit' 'Cabin' 'Roof' 'Palace' 'Full Floor' 'Bulk Rent Unit'
 'Bungalow']
--------------------------------------------------
Column: price_egp
[24500000.  5145000. 10800000. ...   705000.    65594.    70650.]
--------------------------------------------------
Column: area_value
[4.450e+02 1.230e+02 2.500e+02 1.360e+02 2.550e+02       nan 2.090e+02
 8.500e+01 2.850e+02 1.440e+02 9.630e+02 3.200e+02 2.650e+02 2.260e+02
 4.150e+02 6.520e+02 1.550e+02 2.800e+02 3.000e+02 3.040e+02 1.380e+02
 1.500e+02 5.600e+01 1.450e+02 8.500e+02 1.200e+02 1.030e+02 1.150e+02
 2.050e+02 1.860e+02 3.400e+01 5.750e+02 2.870e+02 1.530e+02 1.900e+02
 2.300e+02 1.280e+02 2.210e+02 2.200e+02 1.920e+02 2.110e+02 1.570e+02
 7.600e+01 1.640e+02 4.500e+01 2.540e+02 4.100e+01 1.000e+02 1.680e+02
 1.620e+02 1.420e+02 1.700e+02 2.020e+02 2.000e+01 3.450e+02 2.450e+02
 2.640e+02 2.100e+02 2.250e+02 1.910e+02 1.210e+02 1.270e+02 1.850e+02
 2.000e+02 1.050e+03 6.000e+02 1.000e+00 4.700e+01 1.990e+02 2.330e+02
 1.600e+02 1.470e+02 5.000e+01 1.300e+02 1.650e+02 2.400e+02 7.300e+01
 4.400e+02 1.310e+02 6.900e+01 9.900e+02 8.300e+01 1.400e+02 5.700e+01
 1.880e+02 4.650e+02 1.820e+02 1.690e+02 2.750e+02 2.950e+02 2.620e+02
 1.760e+02 3.500e+02 2.150e+02 3.380e+02 1.100e+02 1.250e+02 1.800e+02
 2.380e+02 1.350e+02 4.000e+01 6.000e+01 8.400e+01 2.780e+02 1.430e+02
 4.500e+02 1.490e+02 1.780e+02 1.120e+03 3.520e+02 2.220e+02 6.200e+02
 7.000e+01 4.550e+02 2.080e+02 7.500e+01 9.600e+01 6.500e+01 4.140e+02
 2.700e+02 3.850e+02 1.400e+03 5.000e+02 4.600e+02 1.000e+03 1.270e+03
 8.000e+01 1.940e+02 1.110e+02 3.070e+02 2.340e+02 1.580e+02 1.980e+02
 1.670e+02 4.390e+02 9.000e+01 9.400e+01 6.600e+01 5.300e+01 6.300e+01
 3.920e+02 1.750e+02 6.090e+02 8.900e+01 2.040e+02 1.730e+02 5.200e+02
 2.130e+02 3.580e+02 1.320e+02 7.700e+01 1.950e+02 2.560e+02 1.160e+02
 4.860e+02 4.200e+02 9.500e+01 4.000e+02 3.310e+02 7.800e+01 1.630e+02
 1.080e+02 2.030e+02 1.560e+02 1.130e+02 3.910e+02 3.320e+02 5.900e+01
 1.970e+02 3.900e+02 1.480e+02 4.720e+02 2.320e+02 2.940e+02 5.800e+01
 4.250e+02 2.970e+02 3.250e+02 1.740e+02 1.520e+02 8.450e+02 3.600e+01
 2.120e+02 2.280e+02 1.590e+02 1.010e+02 8.800e+01 1.260e+02 3.930e+02
 4.400e+01 5.500e+02 1.610e+02 2.350e+02 1.790e+02 2.070e+02 3.700e+02
 1.060e+02 3.760e+02 2.440e+02 6.100e+01 1.960e+02 8.700e+01 5.500e+01
 1.120e+02 1.890e+02 2.580e+02 4.800e+02 3.550e+02 6.400e+01 2.600e+02
 2.660e+02 9.000e+02 3.200e+01 5.100e+01 2.510e+02 1.090e+02 6.500e+02
 3.400e+02 1.025e+03 3.210e+02 7.200e+01 1.220e+02 1.170e+02 3.060e+02
 2.390e+02 2.370e+02 9.100e+01 1.000e+01 1.510e+02 4.200e+01 2.100e+01
 2.500e+01 1.540e+02 5.400e+01 3.480e+02 1.720e+02 3.350e+02 3.160e+02
 1.223e+03 2.140e+02 1.330e+02 4.510e+02 3.460e+02 3.870e+02 1.020e+02
 2.360e+02 1.710e+02 9.300e+01 2.740e+02 2.060e+02 4.750e+02 4.280e+02
 3.700e+01 8.600e+01 8.100e+01 3.810e+02 2.630e+02 5.490e+02 3.000e+01
 1.189e+03 1.660e+02 6.200e+01 1.240e+02 2.690e+02 8.000e+02 1.460e+02
 2.000e+00 3.650e+02 1.770e+02 3.600e+02 3.030e+02 2.890e+02 4.960e+02
 3.560e+02 9.700e+01 3.050e+02 1.040e+02 4.600e+01 1.370e+02 2.290e+02
 6.650e+02 1.180e+02 7.900e+01 3.500e+01 9.200e+01 3.300e+02 4.130e+02
 4.180e+02 2.420e+02 2.820e+02 2.900e+02 1.830e+02 1.290e+02 1.140e+02
 1.050e+02 2.980e+02 4.850e+02 8.080e+02 1.870e+02 9.800e+01 5.200e+01
 7.000e+02 5.090e+02 4.660e+02 2.470e+02 9.700e+02 2.460e+02 2.860e+02
 2.480e+02 7.310e+02 4.210e+02 2.610e+02 2.300e+01 1.810e+02 2.810e+02
 1.200e+03 3.410e+02 3.150e+02 1.410e+02 8.460e+02 2.180e+02 5.800e+02
 2.160e+02 3.270e+02 1.340e+02 2.760e+02 2.920e+02 3.860e+02 2.770e+02
 5.040e+02 2.430e+02 7.170e+02 4.300e+01 7.200e+02 1.400e+01 2.670e+02
 2.240e+02 3.220e+02 4.020e+02 1.070e+02 2.170e+02 1.100e+01 3.100e+02
 2.190e+02 3.170e+02 7.570e+02 3.840e+02 1.840e+02 2.270e+02 4.900e+01
 4.120e+02 2.200e+01 3.360e+02 8.250e+02 3.130e+02 3.120e+02 2.840e+02
 2.230e+02 8.200e+01 7.100e+01 1.930e+02 4.870e+02 4.110e+02 6.800e+01
 6.170e+02 3.830e+02 3.440e+02 4.840e+02 2.790e+02 2.530e+02 9.900e+01
 2.730e+02 3.900e+01 3.340e+02 4.820e+02 4.170e+02 6.860e+02 3.740e+02
 3.880e+02 3.800e+02 1.450e+03 1.700e+03 1.300e+03 1.100e+03 5.600e+02
 1.390e+02 3.530e+02 7.400e+01 4.490e+02 2.520e+02 4.270e+02 7.500e+02
 6.700e+01 2.910e+02 2.310e+02 6.330e+02 4.330e+02 3.300e+01 7.380e+02
 6.800e+02 1.550e+03 6.720e+02 4.070e+02 9.500e+02 2.830e+02 3.540e+02
 1.058e+03 2.720e+02 4.050e+02 4.100e+02 3.020e+02 3.780e+02 4.580e+02
 2.930e+02 1.700e+01 3.190e+02 3.260e+02 4.800e+01 1.190e+02 6.300e+02
 3.750e+02 6.150e+02 1.500e+03 1.075e+03 6.600e+02 4.640e+02 6.250e+02
 6.780e+02 6.080e+02 3.470e+02 6.100e+02 5.280e+02 4.410e+02 4.700e+02
 2.010e+02 4.540e+02 3.370e+02 1.600e+03 6.700e+02 4.260e+02 7.320e+02
 2.710e+02 3.570e+02 8.740e+02 4.230e+02 8.750e+02 5.400e+02 2.490e+02
 3.590e+02 3.390e+02 5.050e+02 5.590e+02 7.600e+02 5.720e+02 3.420e+02
 3.610e+02 3.090e+02 4.290e+02 3.510e+02 8.700e+02 8.060e+02 2.570e+02
 8.170e+02 5.700e+02 6.280e+02 3.490e+02 1.600e+01 4.900e+02 3.640e+02
 2.633e+03 8.320e+02 6.960e+02 6.770e+02 7.800e+02 2.880e+02 7.400e+02
 3.110e+02 5.190e+02 3.730e+02 4.370e+02 3.080e+02 4.470e+02 3.660e+02
 5.310e+02 3.630e+02 3.140e+02 4.010e+02 1.800e+03 2.200e+03 4.980e+02
 4.220e+02 8.100e+02 3.430e+02 4.300e+02 3.890e+02 2.990e+02 9.250e+02
 1.150e+03 1.647e+03 4.240e+02 7.900e+02 6.400e+02 9.870e+02 7.450e+02
 2.590e+02 4.350e+02 5.100e+02 2.410e+02 4.160e+02 7.430e+02 4.680e+02
 5.070e+02 3.240e+02 1.060e+04 3.770e+02 1.650e+03 3.330e+02 4.060e+02
 6.750e+02 1.350e+03 9.350e+02 4.950e+02 4.910e+02 5.620e+02 3.950e+02
 5.350e+02 5.390e+02 3.820e+02 5.550e+02 5.600e+03 4.590e+02 3.710e+02
 1.683e+03 2.000e+03 5.580e+02 1.352e+03 1.255e+03 2.900e+03 4.670e+02
 1.240e+03 5.140e+02 5.300e+02 6.010e+02 8.010e+02 1.801e+03 1.001e+03
 4.710e+02 8.200e+02 5.330e+02 3.720e+02 3.620e+02 9.300e+02 3.690e+02
 5.250e+02 5.180e+02 6.440e+02 1.660e+03 1.470e+03 9.100e+02 5.220e+02
 4.080e+02 3.940e+02 8.150e+02 7.700e+02 7.770e+02 2.680e+02 5.150e+02
 9.610e+02 5.360e+02 3.230e+02 4.000e+03 6.820e+02 6.360e+02 3.100e+01
 4.610e+02 2.500e+03 9.530e+02 3.010e+02 1.324e+03 1.640e+03 1.017e+03
 5.000e+00 5.130e+02 6.060e+02 6.900e+02 2.960e+02 1.200e+04 9.430e+02
 5.170e+02 5.030e+02 5.510e+02 6.310e+02 9.660e+04 4.940e+02 6.810e+02
 2.100e+04 1.900e+03 4.200e+04 5.940e+02 7.480e+02 3.670e+02 5.160e+02
 1.325e+03 3.280e+02 4.310e+02 4.800e+03 4.810e+03 6.070e+02 3.852e+04
 4.780e+02 5.480e+02 2.700e+01 1.360e+03 4.440e+02 2.600e+01 1.250e+03
 1.180e+03 4.560e+02 6.480e+02 1.754e+03 4.320e+02 4.420e+02 1.500e+01
 2.800e+01 5.520e+02 5.650e+02 6.670e+02 7.090e+02 1.225e+03 6.530e+02
 3.500e+03 7.050e+02 9.400e+02 7.350e+02 8.640e+02 4.730e+02 4.340e+02
 4.990e+02 4.920e+02 4.810e+02 5.900e+02 4.480e+02 6.910e+02 6.430e+02
 6.870e+02 4.040e+02 5.640e+02 3.180e+02 5.880e+02 3.680e+02 7.850e+02
 4.090e+02 1.850e+03 2.400e+01 5.450e+02 7.760e+02 1.200e+01 4.930e+02
 6.230e+02 6.180e+02 7.590e+02 7.010e+02 3.000e+03 6.050e+02 8.400e+02
 7.730e+02 8.800e+02 7.530e+02 3.990e+02 8.050e+02 8.350e+02 9.600e+02
 6.660e+02 4.630e+02 5.060e+02 5.020e+02 7.100e+02 6.000e+00 4.570e+02
 5.810e+02 3.000e+00 5.540e+02 6.120e+02 6.270e+02 1.400e+04 7.160e+02
 3.790e+02 1.010e+03 7.150e+02 6.880e+02 7.650e+02 9.620e+02 7.300e+02
 7.740e+02 1.378e+03 8.420e+02 3.980e+02 5.120e+02 4.970e+02 6.680e+02
 4.770e+02 1.080e+03 3.960e+02 1.649e+03 8.520e+02 8.510e+02 5.240e+02
 4.880e+02 4.520e+02 7.180e+02 7.610e+02 1.271e+03 1.115e+03 6.020e+02
 6.510e+02 7.290e+02 2.700e+03 8.600e+02 5.080e+02 9.800e+02 2.400e+03
 3.290e+02 1.920e+03 1.012e+03 5.820e+02 2.900e+01 4.620e+02 4.460e+02
 4.740e+02 5.430e+02 1.051e+03 5.630e+02 9.200e+02 1.245e+03 6.560e+02]
--------------------------------------------------
Column: bedrooms
['3' '2' '4' nan '6' '5' 'studio' '7' '1' '7+']
--------------------------------------------------
Column: bathrooms
['6' '2' '4' nan '1' '3' '7+' '5' '7' 'none']
--------------------------------------------------
Column: city
['Cairo' 'Giza' nan 'North Coast' 'Red Sea' 'Suez' 'Alexandria' 'Sharqia'
 'South Sainai' 'Qalyubia' 'Matrouh' 'Al Daqahlya' 'Demyat']
--------------------------------------------------
Column: town
['New Cairo City' 'Sheikh Zayed City' nan 'Sidi Abdel Rahman'
 '6 October City' 'Hurghada' 'El Khalifa' 'Qesm Ad Dabaah'
 'Qesm Marsa Matrouh' 'Ras Al Hekma' 'New Capital City' 'Al Ain Al Sokhna'
 'Mostakbal City - Future City' 'New Heliopolis' 'Badr City' 'El Nozha'
 'Hay El Haram' 'Hadayek El Ahram' 'Ring Road' 'Al Alamein' 'Shorouk City'
 'Nasr City' 'Madinaty' 'Alexandria Compounds' 'Mokattam' 'Sidi Heneish'
 'Mohandessin' 'Heliopolis - Masr El Gedida' 'Hay El Maadi' 'Hay Sharq'
 'Hay Wasat' 'Noor City' 'Zamalek' 'Borg El Arab City'
 '10th of Ramadan City' 'Al Agouza' 'Ras Sedr'
 'Cairo Alexandria Desert Road' 'Obour City' 'Marsa Alam'
 'Qesm Borg El Arab' 'Ganoub El Giza' 'Dokki' 'New Obour City'
 'Hay Al Amereyah' 'Marsa Matrouh' 'New Mansoura' 'Hay Awal El Montazah'
 'Markaz Al Hamam' 'Hay Than El Montazah' 'Garden City'
 'Hay Masr El Kadima' 'Hay El Gomrok' 'Downtown'
 'Cairo - Ismailia Desert Road' 'North Coast Resorts' 'New Damietta'
 'Hay El Zaytoun' 'Hacienda' 'Hay El Manial' 'Hay Al Agami'
 'Al Salam City' 'Hay Helwan' 'El Sayeda Zainab' 'Shobra Al Khaimah'
 'Ain Shams' 'Ataqa District' 'Bulaq Abo El Ela']
--------------------------------------------------
Column: district
['The 5th Settlement' 'Sheikh Zayed Compounds' nan '12th District' 'Amwaj'
 '6 October Compounds' 'El Gouna' 'Al Abageyah' 'Swan Lake North Coast'
 'Silver Sands' 'Hadayek October' 'Mountain View' 'El Katameya' 'DeJoya 4'
 'Telal Al Sokhna' 'The 6th Settlement' 'Namya West' 'Saada Compound'
 'New Capital Compounds' 'The 1st Settlement' 'Hyde Park'
 'Hurghada Resorts' 'North Investors Area' 'Mostakbal City Compounds'
 '6th District' '26th of July Corridor' 'El Motamayez District' 'Ivoire'
 'El Kawther District' 'Al Ahyaa District' 'El Yasmeen' 'Sahl Hasheesh'
 'Makadi' 'South Investors Area' 'Marassi' 'New Zayed City'
 'Sheraton Al Matar' 'El Haram' 'Gate 4 - Mena' 'New Heliopolis Compounds'
 'Al Narges' 'Mountain view' 'Tag Sultan' 'Marina' 'La vista Ras El Hikma'
 'New Alamein City' 'El Shorouk Compounds' '8th Zone' 'Hacienda Bay'
 'Fayoum Desert road' 'Northern Expansions' 'Stella Di Mare' 'Privado'
 'El Hegaz Square' 'Koun' 'Palm Hills' 'IL Monte Galala' '6th Zone'
 'Al Rehab' 'The 3rd Settlement' 'El Hegaz District' 'Uptown Cairo'
 'El Helal' 'Fouka Bay' 'R8' 'Salt' 'Seashore' 'South Dahshur Link' 'R3'
 '10th District' 'Golf Porto Marina' 'Stella Heights' 'Rabaa Al Adaweyah'
 'Suez Road' 'Viva Al Sokhna Resort and Spa' 'Lasirena Palm Beach'
 'Sage Lakes Residence' 'Al Wahat Road' 'Sheraton Rd' 'South Med'
 'El Hadaba District' 'Lumia Lagoons' 'Beit Al Bahr' 'Magawish'
 'Youssef Afifi Road' 'Lebanon St.' 'Safaga' 'June' 'El Lotus'
 'Ganoob El Acadimia' 'El Banafseg' 'Al Andalus District'
 'Bluemar Wadi Degla' 'Piacera' 'Almazah' 'La Vista'
 'Cairo Alexandria Desert Road' '17th District' 'Ogami' 'Arabia Area'
 'Sarayat Al Maadi' 'Seashell' 'The Valleys' '1st District' 'Janaklees'
 'Long Beach Resort' 'Intercontinental District' 'Azha' 'Smouha'
 'Camp Chezar' 'Al Masyaf' 'Solare' 'Hacienda Waters' 'Direction White'
 'Ring Road' 'Azha North' 'Granville' 'Soul North Coast' 'Sawary'
 'Alex West' 'Glim' 'Roushdy' 'Garden Residence' '3rd District West'
 'Riviera City' 'Park View Haptown' 'Al Quds Al Sharif St.' 'New Maadi'
 'Faisal' 'El Gezirah St.' 'Abou Al Feda St.' 'The Residences'
 'Playa Resort' 'Zahra' 'Borg El Arab' 'Jaz Almaza Beach' 'Boardwalk'
 'Zezenia 10th of Ramadan' 'Jaz Little Venice Golf' 'LYV' '14th District'
 '16th District' 'Sidi Gaber' 'Saba Basha' 'Gate 2 - Ahmose' 'Almaza Bay'
 'Al Esraa St.' 'Jebal El Sokhna' 'Ghazala Bay' 'Porto Sokhna'
 'Abou al mahasen al shazli St.' 'Ismail Mohamed St.' 'R5'
 'Ext North Inves Area' 'Hacienda West' 'Abou El Houl' '8th District'
 'Cali Coast' 'D-Bay' 'Naia bay' 'West Somid' 'Porto Marina'
 'La Vista Cascada' 'Ramla Lakeside' 'New October City' 'Romance' 'Lavaya'
 '4th District' 'Heliopolis Square' 'Gaia' 'Zahraa El Maadi'
 'Nasr City Compounds' 'Fleming' 'Kai Sokhna' 'Raas Matarma' 'Sea View'
 'Remal' 'Youd' 'The Med' '10th Zone' '11th District' 'Bella Vento Galala'
 '13th District' 'Tharwat' 'Degla' 'La Siesta' 'Hacienda White'
 'Al Motamayez District' 'Tawny' 'New Narges' 'Mohamed Mazhar St.'
 'Al Hegaz Road' 'Al Kamel Mohamed St.' 'Ras Sedr' 'Jefaira'
 'Al Mansour Mohamed St.' 'R4' 'Family Housing' 'Ceaser' 'Ein Bay 2'
 'Bella East' 'Maadi' 'Mubarak Neighborhood' 'Aziz Abaza St.' 'Sidi Kerir'
 'Ibrahimia' 'Bianchi' 'El Korba' 'Heaven Beach' 'Laurent'
 'Al Hassani St.' 'Esraa Al Moalemeen St.' 'Giza District'
 'Mohi Al Din Abou El Ezz St.' 'Mosadak St.' 'El Nady District'
 'Shores North Coast' 'North Code' 'Ahmed Orabi St.' 'Bait Alwatan'
 'Al Amal St.' 'North Rehab' 'Venecia Bent Al Sultan' 'Green City'
 'Q North' 'Youth Residence' 'Cape Bay Sokhna' 'Stella Marina'
 '9th District' 'King Mariout' 'Lasirena' 'Al Hadaba Al Olya'
 'Al Hadaba Al Wosta' 'Green Belt' 'Lebanon Square'
 'El Motamayez District North' 'Lazorde Bay' 'Gate 1 - Khofo'
 'Celebration West Beach' 'Sedra' 'The Pearl New Mansoura' 'Amman St.'
 'Gameat Al Dewal Al Arabeya St.' 'Shehab St.' 'Al Thawra Square'
 'Al Mathaf Al Zerai St.' 'Mostafa Mahmoud Square' 'Miami' 'Ramla'
 'The Groove' '7th District' 'Shooting Club Street' 'Al Hegaz St.'
 '2nd District' 'Marsa Baghush' 'Marseilia Beach 4' 'San Stefano' 'Horus'
 'Bowling St.' 'Al Hosary' 'Al Mesaha St.'
 'Al Batal Ahmed Abd El Aziz St.' 'Ahmed Heshmat St.' 'Murano Wadi Degla'
 '3rd District' 'Al Maamoura' 'Kamal Al Tawil St. (El Montazah)'
 'Baymount' 'City Center 1' 'Swan Lake West'
 'O NINE by Miqaat Developments' 'Marina Wadi Degla' 'Asafra'
 'LVLS By Mountain View' 'Bolkly' 'Mivida Gardens' 'Ibn Zinky St.'
 'Mohamed Anis St.' 'Bungalows' 'Masaken Al Mohandesin' 'Syria St.'
 'Cecilia Lagoons' 'Zezenia' 'Hacienda Heneish' 'Marseilia Beach 5'
 'Sidi Beshr' 'Coral Sea' 'Garden City St.' 'Hadayek El Maadi'
 'Palm Beach' 'Nile Corniche St.' 'Blue Blue' 'Mar Bay' '1st Area'
 'Ard El Golf' 'Bianchi Ilios' 'Manteqet Al Cinema' 'Marsa Naqari'
 'Saint Fatima Square' 'Malibu' 'Zahraa Masr El Kadima' 'Blumar'
 'East The Academy' 'Sporting' 'Janna' 'El Mahkama Square' '2nd Area'
 '5th District' 'Areej' 'Al Ein Bay' 'Seyouf' 'Moharam Bek' 'Victoria'
 'Nile St.' '5th Area' 'Roxy' 'Al Nasr St.' 'Hacienda Red'
 'Stella Sidi Abdel Rahman' 'Ahmed Basha St.' 'Safia' 'Veranda Smouha'
 'Tanta St.' '6 October- Wadi El Natroun Road' 'El Mansheya'
 'Palm Capital' 'El Shatby' 'Lakehouse Compound' 'Obour Market'
 'Geziret Al Arab St. (El Mohandes Mohamed Hassan Helmy)'
 'Gate 4 old - Horus' '7th Area' 'Cleopatra' 'Shababeek compound'
 'Al Sheikh Al Maraghi St.' 'Nozha' 'Sphinx Square' 'Port Saeed Square'
 'Haeet Al Tadres St.' 'Gate 3 old - Khafre' 'El Mandara' 'Golf City'
 'Nile Boulevard' 'Abou Al Karamat St.' 'Mustafa Kamel' '6th Area East'
 'Qasr El Nil' 'Iran St.' '4th Area' 'Abd Al Hameed Soliman St.'
 'Dimashq St.' 'Azarita' 'Gate 3 - Menkaure' '9th Area'
 'Gamaiet Ahmed Orabi' 'Stella Heliopolis' 'Ashgar Heights'
 'Neighborhood 26' 'Agora' 'Zahraa Madinat Nasr' 'Al Tahrir St.'
 'Beit Al Wattan' 'Mousa Coast' 'Raml Station' 'El Zaytoun'
 'Downtown Marina' 'Al Nadi Al Ahly' 'katameya coast' 'Farrah 1'
 'Al Gamea Square' 'Villagio' 'Emirates Heights' 'Seazen'
 'Waslet Dahshur Road' 'Al Sokhna Hills' 'Riviera Beach' 'Ivy' 'Malaz'
 'SAADA' 'Haven' 'Shagaret Al Dor St.' 'Carnelia' 'Telal Alamein'
 'V Residences' 'G-Bay' 'Athar El Nabi' 'Bellagio' 'Aroma Residence'
 'Skala Mountain View Ras El Hikma' 'Lugano Al Galala' 'Golden Beach 2'
 'Plage' 'Eelaf Compound' 'Mahmoud Azmy St.' 'R7' 'Skyramp'
 '15th District' 'Rewaya' 'Al Hekma St.' 'Nadi Al Zamalek St.' '9th Zone'
 'The Waterway' 'Lake Residence' 'Porto Matrouh' 'La Jolie'
 'El Laselky St.' 'EKO Resort' 'Evia' 'El Manial' 'Okardia' 'Aswan Square'
 'Oia Towers' '2nd District West' 'Diplo East' 'Downtown Area'
 'Mountain View Grand Valley' 'El Nozha El Gadida' 'Movenpick Sokhna'
 'The Harv' '26th District - Spanish Neighborhood' 'Al Hanouvel'
 'Al Mansoureya' 'Bahgat Ali St. (Ebn Al Nabeh)' '6th Area West'
 'Empire Resort' 'Coronado Marina' 'Civ West' 'Boho' '8th Area' 'Al Rawda'
 'Al Sahaba Mosque St.' 'Azzar Islands' 'Ain El Sera' '1st Zone'
 'Coronado Beach' 'Abu Qir' 'Abd Al Moneim Riad St.' 'Alura'
 'Al Gabalaya St.' 'The Islands' 'Orla Residence' 'El Herafeen' 'Orlando'
 'Blue Bay Asia' 'Aquarius' 'Al Bashayer District' 'Helwan'
 '4th District West' 'Caesar' 'Al Fawakeh St.' 'Triumph Square'
 'Ahmed Sabry St.' 'Al Malek El Fadl St.' 'Al Eini'
 'Abdel Moneim Riad St.' 'Hassan Sabri St.'
 'Al Gezira El Wosta St. (Yousef Kamel)' 'El Roda' 'Down Town'
 'Al Masjid Al Aqsa St.' 'Rashdan St.' 'Marina Wadi Al Dome'
 'Bahaa Eldeen Krakoush St.' 'Mohamed Maraashly St.' 'Hassan Assem St.'
 'White Nile St.' 'Abdel Rahim Sabry St.' 'Shafik Mansour St.'
 'Al Zahraa St.' 'Al Dokki St.' 'Taha Hussein St.' 'Diplomatic 3'
 'El Gazaer St.' 'Al Thawra St.' 'Nawal St.' 'Al Aanab St.'
 'Ahmed Ragheb St.' 'El Fustat ( Coptic Cairo )' 'Gesr Suez St.'
 'Brazil St.' 'Al Aziz Othman St.' 'Sri Lanka St.'
 'Gamal Al Din Abou Al Mahasen Square' 'Al Sadd Al Aali St.' 'Tiamo City'
 'Mohamed Abdel Wahab St.' 'Zakaria Rizk St.' '26th July St.'
 'Al Sheikh Al Marsafi St.' 'Maspero Triangle' 'Yehia Ibrahim St.'
 'Al Saleh Ayoub St.' 'Al Borg St.' 'Amberville' 'Al Morsaleen St.'
 'Ibn Maysser St.' 'Al Adel Abu Bakr St.' 'Marassi Bay' 'Stanley'
 'Salah Al Din St.' 'Feini Square' 'Mohammed Thakeb St.'
 'Abdallah Al Kateb St. ( Hendawi )' 'Waboor Elmayah' 'Al Nabatat St.'
 'Shohadaa Al Mohandeseen St.' 'Al Sefarat District' 'El Tawfik City'
 'Cornish El Nile St.' 'Al Bergas St.' 'Charles De Gaulle St.'
 'Oasis District' 'Seasons Country Club' 'Nadi Al Sekka Al Hadid'
 'Al Gazaer St.' 'Zaki Ali St.' 'El Estad' 'Samir Zaki St.'
 'Palm Springs Compound' 'Backus']
--------------------------------------------------
Column: completion_status
['completed' 'off_plan' nan 'completed_primary' 'off_plan_primary']
--------------------------------------------------
Column: listed_date
['2026-03-03T19:15:06Z' '2026-03-04T11:24:23Z' '2026-03-04T14:03:51Z' ...
 '2026-02-07T16:31:32Z' '2026-02-07T16:29:24Z' '2026-02-07T16:26:50Z']
--------------------------------------------------
Column: furnished
[nan 'PARTLY' 'YES' 'NO']
--------------------------------------------------
Column: amenities
["Balcony | Built in Wardrobes | Covered Parking | Maids Room | Private Garden | Private Pool | Shared Pool | Study | View of Water | Security | View of Landmark | Walk-in Closet | Shared Gym | Shared Spa | Children's Pool | Lobby in Building"
 "Balcony | Built in Wardrobes | Central A/C | Covered Parking | Shared Pool | Security | Shared Spa | Shared Gym | View of Landmark | Lobby in Building | Children's Pool"
 "Balcony | Built in Wardrobes | Central A/C | Covered Parking | Kitchen Appliances | Maids Room | Private Garden | Private Pool | Shared Pool | Study | View of Water | Security | Shared Spa | Shared Gym | Walk-in Closet | View of Landmark | Lobby in Building | Children's Pool"
 ...
 "Balcony | Central A/C | Covered Parking | Kitchen Appliances | Built in Wardrobes | Maids Room | Private Garden | Study | View of Water | Security | Shared Spa | Shared Gym | Walk-in Closet | Lobby in Building | View of Landmark | Children's Pool"
 'Balcony | Kitchen Appliances | Covered Parking | Central A/C'

In [ ]:
for col in df.columns:
    print(f'For column {col}\n------------------\n')
    print(df[col].value_counts())
    print('\n')

For column category
------------------

category
rent    19910
buy     19803
Name: count, dtype: int64


For column property_type
------------------

property_type
Apartment          25211
Villa               5652
Townhouse           2187
Chalet              1661
Duplex              1541
Twin House          1426
Penthouse           1240
iVilla               517
Hotel Apartment      107
Roof                  57
Whole Building        40
Land                  29
Cabin                 19
Palace                15
Half Floor             3
Bulk Sale Unit         3
Bungalow               2
Full Floor             1
Bulk Rent Unit         1
Name: count, dtype: int64


For column price_egp
------------------

price_egp
50000.0     874
35000.0     863
55000.0     856
45000.0     846
60000.0     822
           ...
60002.0       1
84312.0       1
60001.0       1
137500.0      1
137000.0      1
Name: count, Length: 4957, dtype: int64


For column area_value
------------------

area_value
200.0     1553
20.0      1378
160.0     1063
150.0     1057
220.0      908
          ...
582.0        1
851.0        1
1920.0       1
963.0        1
852.0        1
Name: count, Length: 734, dtype: int64


For column bedrooms
------------------

bedrooms
3         18189
2          9418
4          6121
5          2128
1          1616
studio     1125
6           670
7           227
7+          184
Name: count, dtype: int64


For column bathrooms
------------------

bathrooms
3       14168
2       11037
4        6135
1        4452
5        2449
6         794
7         380
7+        260
none        8
Name: count, dtype: int64


For column city
------------------

city
Cairo           25865
Giza             9537
North Coast      1809
Red Sea          1430
Suez              517
Alexandria        468
Qalyubia           44
South Sainai       32
Sharqia             5
Matrouh             3
Al Daqahlya         1
Demyat              1
Name: count, dtype: int64


For column town
------------------

town
New Cairo City       19738
Sheikh Zayed City     5388
6 October City        3836
Hurghada              1422
Madinaty              1204
                     ...
El Sayeda Zainab         1
Shobra Al Khaimah        1
Ain Shams                1
Ataqa District           1
Bulaq Abo El Ela         1
Name: count, Length: 67, dtype: int64


For column district
------------------

district
The 5th Settlement        13082
Sheikh Zayed Compounds     3744
6 October Compounds        1485
North Investors Area       1180
Privado                    1007
                          ...
Jebal El Sokhna               1
Seasons Country Club          1
Oasis District                1
Charles De Gaulle St.         1
Cornish El Nile St.           1
Name: count, Length: 519, dtype: int64


For column completion_status
------------------

completion_status
completed            10135
completed_primary     4304
off_plan_primary      4138
off_plan              1186
Name: count, dtype: int64


For column listed_date
------------------

listed_date
2026-02-09T11:27:08Z    13
2026-03-04T12:12:21Z    11
2026-03-03T12:16:32Z    10
2026-03-04T11:52:42Z    10
2026-02-10T13:23:33Z    10
                        ..
2026-03-02T11:55:34Z     1
2026-03-02T11:55:33Z     1
2026-03-02T11:55:32Z     1
2026-03-02T11:55:16Z     1
2026-03-02T11:55:56Z     1
Name: count, Length: 36255, dtype: int64


For column furnished
------------------

furnished
YES       12719
NO        11033
PARTLY     7576
Name: count, dtype: int64


For column amenities
------------------

amenities
Balcony | Built in Wardrobes | Central A/C | Covered Parking | Kitchen Appliances | Maids Room | Private Garden | Private Pool | Shared Pool | Study | View of Water | Security | Shared Spa | Shared Gym | Walk-in Closet | View of Landmark | Lobby in Building | Children's Pool    1467
Balcony | Security                                                                                                                                                                                                                                                                     1182
Balcony                                                                                                                                                                                                                                                                                1155
Balcony | Security | Lobby in Building                                                                                                                                                                                                                                                  255
Security                                                                                                                                                                                                                                                                                253
                                                                                                                                                                                                                                                                                       ...
Balcony | Private Garden | Shared Pool | Study | View of Water | Security | Shared Spa | Shared Gym | Children's Pool | Lobby in Building                                                                                                                                                 1
Balcony | Covered Parking | Study | Shared Pool | Lobby in Building | View of Landmark | Walk-in Closet | Shared Gym                                                                                                                                                                      1
Balcony | Built in Wardrobes | Central A/C | Covered Parking | Maids Room | Private Garden | View of Water | Security | Walk-in Closet | Lobby in Building                                                                                                                                1
Balcony | Covered Parking | Shared Pool | Study | Shared Gym | Children's Pool | Shared Spa | Security | View of Water                                                                                                                                                                    1
Balcony | Built in Wardrobes | Covered Parking | Central A/C | Maids Room | Private Garden | Kitchen Appliances | Private Pool | Shared Pool | Study | View of Water | Security | Shared Spa | Walk-in Closet | Shared Gym | View of Landmark | Lobby in Building | Children's Pool       1
Name: count, Length: 17995, dtype: int64


For column payment_method
------------------

payment_method
cash                   12806
cash | installments     3758
installments            3375
Name: count, dtype: int64

Price and Area Statistics — examining the distribution, averages, and variations of property prices and areas.

In [ ]:
# بيع
df[df['category']=='buy']['price_egp'].describe()

count    1.980200e+04
mean     1.585172e+07
std      3.269793e+07
min      1.131160e+05
25%      5.280000e+06
50%      9.100000e+06
75%      1.700000e+07
max      1.000000e+09
Name: price_egp, dtype: float64

In [ ]:
# إيجار
df[df['category']=='rent']['price_egp'].describe()

count    1.991000e+04
mean     1.685398e+05
std      3.249946e+06
min      1.300000e+03
25%      4.000000e+04
50%      6.500000e+04
75%      1.000000e+05
max      3.050000e+08
Name: price_egp, dtype: float64

In [ ]:
df[df['category']=='buy']['area_value'].describe()

count    19802.000000
mean       216.985658
std       1096.080842
min          1.000000
25%        115.000000
50%        166.000000
75%        240.000000
max      96600.000000
Name: area_value, dtype: float64

In [ ]:
df[df['category']=='rent']['area_value'].describe()

count    19910.000000
mean       219.972677
std        155.985595
min          1.000000
25%        144.000000
50%        186.000000
75%        250.000000
max       3500.000000
Name: area_value, dtype: float64

Property Type Classification (Feature Engineering) — transforming and organizing property categories into structured features for analysis and modeling.

In [ ]:
def categorize_property(x):
    if x in ['Apartment', 'Duplex', 'Penthouse', 'Roof']:
        return 'Residential'

    elif x in ['Villa', 'Twin House', 'Townhouse', 'iVilla']:
        return 'Villa_Compound'

    elif x in ['Chalet', 'Cabin']:
        return 'Coastal'

    elif x in ['Hotel Apartment', 'Whole Building', 'Bulk Sale Unit',
               'Bulk Rent Unit', 'Full Floor', 'Half Floor']:
        return 'Investment'

    elif x in ['Land', 'Palace', 'Bungalow']:
        return 'Land_Luxury'

    else:
        return 'Unknown'


# تطبيق
df['property_group'] = df['property_type'].fillna('Unknown').apply(categorize_property)

Filtering Unrealistic Data — removing inconsistent, invalid, or illogical records to improve data quality and analysis accuracy.

In [ ]:
df = df[
    (
        ((df['category'] == 'buy') & (df['price_egp'] >= 500_000)) |
        ((df['category'] == 'rent') & (df['price_egp'] >= 5_000))
    )
    &
    (df['area_value'] >= 30)
]

df = df.dropna(subset=['price_egp', 'area_value'])

Price and Area Categorization — grouping prices and property areas into meaningful ranges to simplify analysis and identify market patterns.

In [ ]:
# ================================
# Price Category
# ================================

# فئات البيع
buy_bins   = [0, 5_000_000, 10_000_000, 20_000_000, float('inf')]
buy_labels = ['Budget', 'Mid-Range', 'Premium', 'Luxury']

# فئات الإيجار
rent_bins   = [0, 30_000, 70_000, 150_000, float('inf')]
rent_labels = ['Budget', 'Mid-Range', 'Premium', 'Luxury']

# تطبيق
df['price_category'] = None

buy_mask  = df['category'] == 'buy'
rent_mask = df['category'] == 'rent'

df.loc[buy_mask, 'price_category'] = pd.cut(
    df.loc[buy_mask, 'price_egp'],
    bins   = buy_bins,
    labels = buy_labels
)

df.loc[rent_mask, 'price_category'] = pd.cut(
    df.loc[rent_mask, 'price_egp'],
    bins   = rent_bins,
    labels = rent_labels
)

# ================================
# Area Category
# ================================

area_bins   = [0, 100, 200, 350, float('inf')]
area_labels = ['Small', 'Medium', 'Large', 'X-Large']

df['area_category'] = pd.cut(
    df['area_value'],
    bins   = area_bins,
    labels = area_labels
)

# ================================
# النتائج
# ================================

print("=" * 40)
print("Price Category:")
print(df.groupby(['category', 'price_category'])
        .size()
        .reset_index(name='count')
        .to_string(index=False))

print("\n" + "=" * 40)
print("Area Category:")
print(df.groupby(['category', 'area_category'])
        .size()
        .reset_index(name='count')
        .to_string(index=False))

========================================
Price Category:
category price_category  count
     buy         Budget   3415
     buy         Luxury   3840
     buy      Mid-Range   5860
     buy        Premium   5135
    rent         Budget   3257
    rent         Luxury   1909
    rent      Mid-Range   8004
    rent        Premium   6691

========================================
Area Category:
category area_category  count
     buy         Small   2716
     buy        Medium   8478
     buy         Large   5154
     buy       X-Large   1902
    rent         Small   1851
    rent        Medium  10173
    rent         Large   5739
    rent       X-Large   2098

/tmp/ipykernel_2659/1710421802.py:57: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(['category', 'area_category'])

In [ ]:
df

,category,property_type,price_egp,area_value,bedrooms,bathrooms,city,town,district,completion_status,listed_date,furnished,amenities,payment_method,property_group,price_category,area_category
0,buy,Duplex,24500000.0,445.0,3,6,Cairo,New Cairo City,The 5th Settlement,completed,2026-03-03T19:15:06Z,NaN,Balcony | Built in Wardrobes | Covered Parking...,cash,Residential,Luxury,X-Large
1,buy,Apartment,5145000.0,123.0,2,2,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,off_plan,2026-03-04T11:24:23Z,PARTLY,Balcony | Built in Wardrobes | Central A/C | C...,cash,Residential,Mid-Range,Medium
2,buy,Apartment,10800000.0,250.0,4,4,Cairo,New Cairo City,The 5th Settlement,completed,2026-03-04T14:03:51Z,NaN,Balcony | Built in Wardrobes | Central A/C | C...,cash,Residential,Premium,Large
3,buy,Apartment,10500000.0,136.0,2,2,Cairo,New Cairo City,The 5th Settlement,completed,2026-03-04T12:38:11Z,YES,Balcony | Built in Wardrobes | Central A/C | C...,cash,Residential,Premium,Medium
4,buy,Villa,19500000.0,255.0,4,4,Cairo,New Cairo City,The 5th Settlement,completed,2026-03-03T09:45:41Z,NaN,Balcony | Built in Wardrobes | Central A/C | C...,cash,Villa_Compound,Premium,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,55000.0,250.0,3,3,Cairo,New Cairo City,Al Rehab,NaN,2026-02-07T16:33:32Z,YES,Balcony | Central A/C | Kitchen Appliances | S...,NaN,Residential,Mid-Range,Large
39709,rent,Apartment,45000.0,180.0,3,3,Giza,6 October City,Cairo Alexandria Desert Road,NaN,2026-02-07T16:32:23Z,YES,Balcony | Built in Wardrobes | Central A/C | C...,NaN,Residential,Mid-Range,Medium
39710,rent,Townhouse,120000.0,320.0,5,5,Giza,6 October City,Cairo Alexandria Desert Road,NaN,2026-02-07T16:31:32Z,YES,Balcony | Central A/C | Covered Parking | Kitc...,NaN,Villa_Compound,Premium,Large
39711,rent,Apartment,50000.0,196.0,2,2,Giza,6 October City,Cairo Alexandria Desert Road,NaN,2026-02-07T16:29:24Z,NO,Balcony | Kitchen Appliances | Covered Parking...,NaN,Residential,Mid-Range,Medium
39712,rent,Apartment,75000.0,144.0,2,2,Cairo,New Cairo City,The 5th Settlement,NaN,2026-02-07T16:26:50Z,YES,Balcony | Built in Wardrobes | Central A/C | C...,NaN,Residential,Premium,Medium

Cleaning City and District Columns — correcting spelling mistakes in city names, standardizing naming formats, and grouping districts with fewer than 50 listings into an “Other” category to reduce noise and improve analysis quality.

In [ ]:
df['city'] = df['city'].replace({
    'South Sainai' : 'South Sinai',
    'Al Daqahlya'  : 'Al Dakahlia',
    'Demyat'       : 'Damietta'
})

df['city'] = df['city'].fillna('Unknown')

In [ ]:
df['town'] = df['town'].fillna('Unknown')

In [ ]:
df['district'] = df['district'].str.strip().str.title()
# 'Mountain view' → 'Mountain View'

In [ ]:
df['district'] = df['district'].fillna('Unknown')

In [ ]:
# أي district عندها أقل من 50 إعلان → Other
counts = df['district'].value_counts()
rare   = counts[counts < 50].index

df['district'] = df['district'].replace(
    dict.fromkeys(rare, 'Other')
)

Cleaning Completion Status — transforming the `completion_status` column into two clearer and more meaningful features:

* `ready_status`: indicates whether the property is ready for delivery or still under construction (`Ready` / `Off Plan`).
* `source_type`: identifies whether the property is listed directly by the developer or by an owner/reseller (`Primary` / `Secondary`).

In [ ]:
# نشوف الـ nan بتيجي من category إيه
print(df[df['completion_status'].isna()]
      ['category']
      .value_counts())

category
rent    19861
buy        39
Name: count, dtype: int64

In [ ]:
# الإيجار → Unknown طبيعي
# البيع   → 39 صف بس، نحذفهم بدل ما نغلط في التصنيف

# حذف الـ 39 صف في البيع اللي عندهم nan
df = df[~((df['category'] == 'buy') &
          (df['completion_status'].isna()))]

# تبسيط القيم لعمودين
df['ready_status'] = df['completion_status'].map({
    'completed'         : 'Ready',
    'completed_primary' : 'Ready',
    'off_plan'          : 'Off Plan',
    'off_plan_primary'  : 'Off Plan'
})
df['ready_status'] = df['ready_status'].fillna('Unknown')

df['source_type'] = df['completion_status'].map({
    'completed'         : 'Secondary',
    'completed_primary' : 'Primary',
    'off_plan'          : 'Secondary',
    'off_plan_primary'  : 'Primary'
})
df['source_type'] = df['source_type'].fillna('Unknown')

Cleaning Furnishing and Payment Method — standardizing furnishing and payment categories, while assigning missing payment values in rental properties as “Cash” since rent is typically paid on a monthly basis.

In [ ]:
print(df[df['furnished'].isna()]
      ['category'].value_counts())

category
buy     7564
rent     145
Name: count, dtype: int64

In [ ]:
print(df[df['payment_method'].isna()]
      ['category'].value_counts())

category
rent    19724
Name: count, dtype: int64

In [ ]:
df['furnished'] = df['furnished'].map({
    'YES'    : 'Furnished',
    'NO'     : 'Unfurnished',
    'PARTLY' : 'Partly Furnished'
})

# buy  nan → 'Not Specified'
# rent nan → 'Not Specified'
# الاتنين نفس المعاملة
df['furnished'] = df['furnished'].fillna('Not Specified')

In [ ]:
df['payment_method'] = df['payment_method'].map({
    'cash'                : 'Cash',
    'installments'        : 'Installments',
    'cash | installments' : 'Both'
})

# rent nan → 'Cash' (منطقي، الإيجار بيدفع شهري)
df.loc[(df['category'] == 'rent') &
       (df['payment_method'].isna()),
       'payment_method'] = 'Cash'

# buy nan → 'Not Specified' (50 صف بس)
df.loc[(df['category'] == 'buy') &
       (df['payment_method'].isna()),
       'payment_method'] = 'Not Specified'

Amenities Extraction
Transforming the amenities column — which contains all property features as text — into separate binary columns (0 or 1) indicating whether a feature exists or not, such as has_balcony, has_private_pool, etc.
It also creates an amenities_count column to represent the total number of available amenities for each property.

In [ ]:
# استخراج أهم المميزات كـ binary columns
amenities_features = [
    'Balcony',
    'Private Pool',
    'Shared Pool',
    'Private Garden',
    'Covered Parking',
    'Security',
    'Shared Gym',
    'Shared Spa',
    'Maids Room',
    'Central A/C',
    'Built in Wardrobes',
    'Kitchen Appliances',
    'View of Water',
    'View of Landmark',
    "Children's Pool",
    'Lobby in Building'
]

for feature in amenities_features:
    col_name = feature.lower()\
                      .replace(' ', '_')\
                      .replace("'", '')
    df[f'has_{col_name}'] = df['amenities']\
        .str.contains(feature, na=False)\
        .astype(int)

# عمود لعدد المميزات الكلي
df['amenities_count'] = df['amenities']\
    .str.split('|')\
    .str.len()\
    .fillna(0)\
    .astype(int)

# حذف العمود الأصلي
df = df.drop(columns=['amenities'])

In [ ]:
df

,category,property_type,price_egp,area_value,bedrooms,bathrooms,city,town,district,completion_status,...,has_shared_spa,has_maids_room,has_central_a/c,has_built_in_wardrobes,has_kitchen_appliances,has_view_of_water,has_view_of_landmark,has_childrens_pool,has_lobby_in_building,amenities_count
0,buy,Duplex,24500000.0,445.0,3,6,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,0,1,0,1,1,1,1,48
1,buy,Apartment,5145000.0,123.0,2,2,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,off_plan,...,1,0,1,1,0,0,1,1,1,33
2,buy,Apartment,10800000.0,250.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,1,1,1,1,1,54
3,buy,Apartment,10500000.0,136.0,2,2,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,1,1,1,1,1,54
4,buy,Villa,19500000.0,255.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,1,1,1,1,1,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,55000.0,250.0,3,3,Cairo,New Cairo City,Al Rehab,NaN,...,0,0,1,0,1,0,1,0,1,17
39709,rent,Apartment,45000.0,180.0,3,3,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,0,0,1,1,1,0,1,0,0,26
39710,rent,Townhouse,120000.0,320.0,5,5,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,1,1,1,1,1,1,1,1,1,48
39711,rent,Apartment,50000.0,196.0,2,2,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,0,0,1,0,1,0,0,0,0,10
39712,rent,Apartment,75000.0,144.0,2,2,Cairo,New Cairo City,The 5Th Settlement,NaN,...,1,0,1,1,1,1,1,1,1,40

Listing Date Analysis — transforming the listing date into separate features such as year, month, and quarter to enable easier and more effective time-based analysis.

In [ ]:
df["listed_date"] = pd.to_datetime(df["listed_date"]).dt.normalize()

In [ ]:
df["year"]  = df["listed_date"].dt.year
df["month"] = df["listed_date"].dt.month

In [ ]:
df["month_name"] = df["listed_date"].dt.month_name()

In [ ]:
df["quarter"] = df["listed_date"].dt.quarter

In [ ]:
df["quarter_name"] = "Q" + df["listed_date"].dt.quarter.astype(str)

In [ ]:
df['listed_date'] = df['listed_date'].dropna()

In [ ]:
df

,category,property_type,price_egp,area_value,bedrooms,bathrooms,city,town,district,completion_status,...,has_view_of_water,has_view_of_landmark,has_childrens_pool,has_lobby_in_building,amenities_count,year,month,month_name,quarter,quarter_name
0,buy,Duplex,24500000.0,445.0,3,6,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,48,2026,3,March,1,Q1
1,buy,Apartment,5145000.0,123.0,2,2,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,off_plan,...,0,1,1,1,33,2026,3,March,1,Q1
2,buy,Apartment,10800000.0,250.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,54,2026,3,March,1,Q1
3,buy,Apartment,10500000.0,136.0,2,2,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,54,2026,3,March,1,Q1
4,buy,Villa,19500000.0,255.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,1,54,2026,3,March,1,Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,55000.0,250.0,3,3,Cairo,New Cairo City,Al Rehab,NaN,...,0,1,0,1,17,2026,2,February,1,Q1
39709,rent,Apartment,45000.0,180.0,3,3,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,0,1,0,0,26,2026,2,February,1,Q1
39710,rent,Townhouse,120000.0,320.0,5,5,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,1,1,1,1,48,2026,2,February,1,Q1
39711,rent,Apartment,50000.0,196.0,2,2,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,0,0,0,0,10,2026,2,February,1,Q1
39712,rent,Apartment,75000.0,144.0,2,2,Cairo,New Cairo City,The 5Th Settlement,NaN,...,1,1,1,1,40,2026,2,February,1,Q1

Cleaning Bedrooms and Bathrooms — converting values like `"studio"` to `0` and `"7+"` to `7`, while filling missing values using the median based on the property type, which provides a smarter and more accurate approach than using a global median.

In [ ]:
df['bedrooms'] = (
    df['bedrooms']
    .replace({'studio': 0, '7+': 7})
    .pipe(pd.to_numeric, errors='coerce')
    .astype('Int64')  # نوع integer يدعم NaN
)

In [ ]:
df["bedrooms"] = df.groupby("property_type")["bedrooms"]\
                   .transform(lambda x: x.fillna(x.median()))

In [ ]:
df["bedrooms"] = df["bedrooms"].round().astype("Int64")

In [ ]:
df['bathrooms'] = (
    df['bathrooms']
    .replace({'none': 0, '7+': 7})
    .pipe(pd.to_numeric, errors='coerce')
    .astype('Int64')  # نوع integer يدعم NaN
)

In [ ]:
df["bathrooms"] = df.groupby("property_type")["bathrooms"]\
    .transform(lambda x: x.fillna(round(x.median())))

Adding Price per Square Meter — creating a highly important feature that allows fair comparison between properties regardless of their size.

In [ ]:
df['price_per_meter'] = df['price_egp'] / df['area_value']

In [ ]:
# معرفة نوع البيانات لكل عمود
print(df.dtypes)

category                               object
property_type                          object
price_egp                             float64
area_value                            float64
bedrooms                                Int64
bathrooms                               Int64
city                                   object
town                                   object
district                               object
completion_status                      object
listed_date               datetime64[ns, UTC]
furnished                              object
payment_method                         object
property_group                         object
price_category                         object
area_category                        category
ready_status                           object
source_type                            object
has_balcony                             int64
has_private_pool                        int64
has_shared_pool                         int64
has_private_garden                      int64
has_covered_parking                     int64
has_security                            int64
has_shared_gym                          int64
has_shared_spa                          int64
has_maids_room                          int64
has_central_a/c                         int64
has_built_in_wardrobes                  int64
has_kitchen_appliances                  int64
has_view_of_water                       int64
has_view_of_landmark                    int64
has_childrens_pool                      int64
has_lobby_in_building                   int64
amenities_count                         int64
year                                    int32
month                                   int32
month_name                             object
quarter                                 int32
quarter_name                           object
price_per_meter                       float64
dtype: object

In [ ]:
df['area_category'] = df['area_category'].astype('object')

In [ ]:
print(df.dtypes)

category                               object
property_type                          object
price_egp                             float64
area_value                            float64
bedrooms                                Int64
bathrooms                               Int64
city                                   object
town                                   object
district                               object
completion_status                      object
listed_date               datetime64[ns, UTC]
furnished                              object
payment_method                         object
property_group                         object
price_category                         object
area_category                          object
ready_status                           object
source_type                            object
has_balcony                             int64
has_private_pool                        int64
has_shared_pool                         int64
has_private_garden                      int64
has_covered_parking                     int64
has_security                            int64
has_shared_gym                          int64
has_shared_spa                          int64
has_maids_room                          int64
has_central_a/c                         int64
has_built_in_wardrobes                  int64
has_kitchen_appliances                  int64
has_view_of_water                       int64
has_view_of_landmark                    int64
has_childrens_pool                      int64
has_lobby_in_building                   int64
amenities_count                         int64
year                                    int32
month                                   int32
month_name                             object
quarter                                 int32
quarter_name                           object
price_per_meter                       float64
dtype: object

In [ ]:
df = df.drop_duplicates()

In [ ]:
df

,category,property_type,price_egp,area_value,bedrooms,bathrooms,city,town,district,completion_status,...,has_view_of_landmark,has_childrens_pool,has_lobby_in_building,amenities_count,year,month,month_name,quarter,quarter_name,price_per_meter
0,buy,Duplex,24500000.0,445.0,3,6,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,48,2026,3,March,1,Q1,55056.179775
1,buy,Apartment,5145000.0,123.0,2,2,Giza,Sheikh Zayed City,Sheikh Zayed Compounds,off_plan,...,1,1,1,33,2026,3,March,1,Q1,41829.268293
2,buy,Apartment,10800000.0,250.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,54,2026,3,March,1,Q1,43200.000000
3,buy,Apartment,10500000.0,136.0,2,2,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,54,2026,3,March,1,Q1,77205.882353
4,buy,Villa,19500000.0,255.0,4,4,Cairo,New Cairo City,The 5Th Settlement,completed,...,1,1,1,54,2026,3,March,1,Q1,76470.588235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,rent,Apartment,55000.0,250.0,3,3,Cairo,New Cairo City,Al Rehab,NaN,...,1,0,1,17,2026,2,February,1,Q1,220.000000
39709,rent,Apartment,45000.0,180.0,3,3,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,1,0,0,26,2026,2,February,1,Q1,250.000000
39710,rent,Townhouse,120000.0,320.0,5,5,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,1,1,1,48,2026,2,February,1,Q1,375.000000
39711,rent,Apartment,50000.0,196.0,2,2,Giza,6 October City,Cairo Alexandria Desert Road,NaN,...,0,0,0,10,2026,2,February,1,Q1,255.102041
39712,rent,Apartment,75000.0,144.0,2,2,Cairo,New Cairo City,The 5Th Settlement,NaN,...,1,1,1,40,2026,2,February,1,Q1,520.833333